name: VM runner test
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  vm-build:
    strategy:
      matrix:
        node: [vm-freebsd-14.2-amd64, vm-netbsd-10.1-amd64, openindiana-hipster-amd64]
    runs-on: ${{ matrix.node }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: accept VMs host key
        run: /vm_exec uname -a
      - name: copy over ourself into VM
        run: /vm_copy_to /xorg-testing etc lib build-*
      - name: execute in VM
        run: /vm_exec "cd /xorg-testing && ./build-testing-jail force"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
